-- =========================================================================
-- Supabase Schema for Masters Kerala RE 2.0 EXPO26 Registrations
-- Execute this SQL in your Supabase SQL Editor: https://supabase.com/dashboard/project/cawacfivjjeyazppekip/sql
-- =========================================================================

-- 1. Pre-Registrations Table
CREATE TABLE IF NOT EXISTS public.pre_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    country_code TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    city TEXT,
    category TEXT,
    days TEXT
);

-- 2. Visitor Registrations Table
CREATE TABLE IF NOT EXISTS public.visitor_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    country_code TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    visit_profile TEXT,
    company_name TEXT,
    designation TEXT,
    address TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    pincode TEXT,
    landmark TEXT,
    days TEXT
);

-- 3. Exhibitor Registrations Table
CREATE TABLE IF NOT EXISTS public.exhibitor_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    designation TEXT,
    company_name TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    address TEXT,
    pincode TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    days TEXT
);

-- Schema Migrations (if tables already exist)
ALTER TABLE public.visitor_registrations ADD COLUMN IF NOT EXISTS days TEXT;
ALTER TABLE public.exhibitor_registrations ADD COLUMN IF NOT EXISTS days TEXT;
ALTER TABLE public.visitor_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'REGISTERED';
ALTER TABLE public.visitor_registrations ADD COLUMN IF NOT EXISTS last_entry_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.visitor_registrations ADD COLUMN IF NOT EXISTS last_exit_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.exhibitor_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'REGISTERED';
ALTER TABLE public.exhibitor_registrations ADD COLUMN IF NOT EXISTS last_entry_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.exhibitor_registrations ADD COLUMN IF NOT EXISTS last_exit_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.pre_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'REGISTERED';
ALTER TABLE public.pre_registrations ADD COLUMN IF NOT EXISTS last_entry_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.pre_registrations ADD COLUMN IF NOT EXISTS last_exit_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.sub_event_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'REGISTERED';
ALTER TABLE public.sub_event_registrations ADD COLUMN IF NOT EXISTS last_entry_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.sub_event_registrations ADD COLUMN IF NOT EXISTS last_exit_at TIMESTAMP WITH TIME ZONE;

-- 5. Entry Exit Logs Table
CREATE TABLE IF NOT EXISTS public.entry_exit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    registration_type TEXT NOT NULL,
    registration_id BIGINT,
    badge_id TEXT,
    attendee_name TEXT NOT NULL,
    mobile TEXT,
    action TEXT NOT NULL, -- 'ENTRY', 'EXIT'
    scanned_by TEXT DEFAULT 'Gate Admin',
    gate_name TEXT DEFAULT 'Main Gate'
);

-- =========================================================================
-- Enable Row Level Security (RLS) & Set Permissive Policies for Form Submissions
-- =========================================================================

ALTER TABLE public.pre_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exhibitor_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entry_exit_logs ENABLE ROW LEVEL SECURITY;

-- Drop Policies if they already exist
DROP POLICY IF EXISTS "Allow public insert to pre_registrations" ON public.pre_registrations;
DROP POLICY IF EXISTS "Allow public select to pre_registrations" ON public.pre_registrations;
DROP POLICY IF EXISTS "Allow public delete to pre_registrations" ON public.pre_registrations;

DROP POLICY IF EXISTS "Allow public insert to visitor_registrations" ON public.visitor_registrations;
DROP POLICY IF EXISTS "Allow public select to visitor_registrations" ON public.visitor_registrations;
DROP POLICY IF EXISTS "Allow public delete to visitor_registrations" ON public.visitor_registrations;

DROP POLICY IF EXISTS "Allow public insert to exhibitor_registrations" ON public.exhibitor_registrations;
DROP POLICY IF EXISTS "Allow public select to exhibitor_registrations" ON public.exhibitor_registrations;
DROP POLICY IF EXISTS "Allow public delete to exhibitor_registrations" ON public.exhibitor_registrations;

DROP POLICY IF EXISTS "Allow public insert to sub_event_registrations" ON public.sub_event_registrations;
DROP POLICY IF EXISTS "Allow public select to sub_event_registrations" ON public.sub_event_registrations;
DROP POLICY IF EXISTS "Allow public delete to sub_event_registrations" ON public.sub_event_registrations;

DROP POLICY IF EXISTS "Allow public insert to entry_exit_logs" ON public.entry_exit_logs;
DROP POLICY IF EXISTS "Allow public select to entry_exit_logs" ON public.entry_exit_logs;
DROP POLICY IF EXISTS "Allow public delete to entry_exit_logs" ON public.entry_exit_logs;

-- Allow Public Inserts, Selects, and Deletes
CREATE POLICY "Allow public insert to pre_registrations" ON public.pre_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to pre_registrations" ON public.pre_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to pre_registrations" ON public.pre_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to visitor_registrations" ON public.visitor_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to visitor_registrations" ON public.visitor_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to visitor_registrations" ON public.visitor_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to exhibitor_registrations" ON public.exhibitor_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to exhibitor_registrations" ON public.exhibitor_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to exhibitor_registrations" ON public.exhibitor_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to sub_event_registrations" ON public.sub_event_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to sub_event_registrations" ON public.sub_event_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to sub_event_registrations" ON public.sub_event_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to entry_exit_logs" ON public.entry_exit_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to entry_exit_logs" ON public.entry_exit_logs FOR SELECT USING (true);
CREATE POLICY "Allow public delete to entry_exit_logs" ON public.entry_exit_logs FOR DELETE USING (true);

-- =========================================================================
-- 1. DELETE EXISTING DUPLICATE DATA (Retains newest row per mobile/email)
-- =========================================================================

-- Deduplicate visitor_registrations
DELETE FROM public.visitor_registrations
WHERE id NOT IN (
    SELECT MAX(id)
    FROM public.visitor_registrations
    GROUP BY mobile
);

DELETE FROM public.visitor_registrations
WHERE email IS NOT NULL AND email <> '' AND id NOT IN (
    SELECT MAX(id)
    FROM public.visitor_registrations
    WHERE email IS NOT NULL AND email <> ''
    GROUP BY email
);

-- Deduplicate exhibitor_registrations
DELETE FROM public.exhibitor_registrations
WHERE id NOT IN (
    SELECT MAX(id)
    FROM public.exhibitor_registrations
    GROUP BY mobile
);

DELETE FROM public.exhibitor_registrations
WHERE email IS NOT NULL AND email <> '' AND id NOT IN (
    SELECT MAX(id)
    FROM public.exhibitor_registrations
    WHERE email IS NOT NULL AND email <> ''
    GROUP BY email
);

-- Deduplicate pre_registrations
DELETE FROM public.pre_registrations
WHERE id NOT IN (
    SELECT MAX(id)
    FROM public.pre_registrations
    GROUP BY mobile
);

DELETE FROM public.pre_registrations
WHERE email IS NOT NULL AND email <> '' AND id NOT IN (
    SELECT MAX(id)
    FROM public.pre_registrations
    WHERE email IS NOT NULL AND email <> ''
    GROUP BY email
);

-- Deduplicate sub_event_registrations
DELETE FROM public.sub_event_registrations
WHERE id NOT IN (
    SELECT MAX(id)
    FROM public.sub_event_registrations
    GROUP BY mobile, COALESCE(event_slug, '')
);

-- =========================================================================
-- 2. CREATE UNIQUE INDEXES FOR DUPLICATE PREVENTION (Mobile & Email)
-- =========================================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_visitor_mobile_unique ON public.visitor_registrations (mobile);
CREATE UNIQUE INDEX IF NOT EXISTS idx_visitor_email_unique ON public.visitor_registrations (email) WHERE email IS NOT NULL AND email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_exhibitor_mobile_unique ON public.exhibitor_registrations (mobile);
CREATE UNIQUE INDEX IF NOT EXISTS idx_exhibitor_email_unique ON public.exhibitor_registrations (email) WHERE email IS NOT NULL AND email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_pre_mobile_unique ON public.pre_registrations (mobile);
CREATE UNIQUE INDEX IF NOT EXISTS idx_pre_email_unique ON public.pre_registrations (email) WHERE email IS NOT NULL AND email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_sub_mobile_event_unique ON public.sub_event_registrations (mobile, COALESCE(event_slug, ''));



