-- =========================================================================
-- Supabase Schema for Masters Kerala RE 2.0 EXPO26 Registrations
-- Execute this SQL in your Supabase SQL Editor: https://supabase.com/dashboard/project/cawacfivjjeyazppekip/sql
-- =========================================================================

-- 1. Pre-Registrations Table
CREATE TABLE IF NOT EXISTS public.pre_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    country_code TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    city TEXT,
    category TEXT,
    days TEXT
);

-- 2. Visitor Registrations Table
CREATE TABLE IF NOT EXISTS public.visitor_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    country_code TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    visit_profile TEXT,
    company_name TEXT,
    designation TEXT,
    address TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    pincode TEXT,
    landmark TEXT,
    days TEXT
);

-- 3. Exhibitor Registrations Table
CREATE TABLE IF NOT EXISTS public.exhibitor_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    designation TEXT,
    company_name TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    address TEXT,
    pincode TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    days TEXT
);

-- Schema Migrations (if tables already exist)
ALTER TABLE public.visitor_registrations ADD COLUMN IF NOT EXISTS days TEXT;
ALTER TABLE public.exhibitor_registrations ADD COLUMN IF NOT EXISTS days TEXT;

-- 4. Sub-Event Registrations Table
CREATE TABLE IF NOT EXISTS public.sub_event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    event_slug TEXT,
    name TEXT NOT NULL,
    country_code TEXT,
    mobile TEXT NOT NULL,
    email TEXT,
    visit_profile TEXT,
    company_name TEXT,
    designation TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT
);

-- =========================================================================
-- Enable Row Level Security (RLS) & Set Permissive Policies for Form Submissions
-- =========================================================================

ALTER TABLE public.pre_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exhibitor_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_event_registrations ENABLE ROW LEVEL SECURITY;

-- Drop Policies if they already exist
DROP POLICY IF EXISTS "Allow public insert to pre_registrations" ON public.pre_registrations;
DROP POLICY IF EXISTS "Allow public select to pre_registrations" ON public.pre_registrations;
DROP POLICY IF EXISTS "Allow public delete to pre_registrations" ON public.pre_registrations;

DROP POLICY IF EXISTS "Allow public insert to visitor_registrations" ON public.visitor_registrations;
DROP POLICY IF EXISTS "Allow public select to visitor_registrations" ON public.visitor_registrations;
DROP POLICY IF EXISTS "Allow public delete to visitor_registrations" ON public.visitor_registrations;

DROP POLICY IF EXISTS "Allow public insert to exhibitor_registrations" ON public.exhibitor_registrations;
DROP POLICY IF EXISTS "Allow public select to exhibitor_registrations" ON public.exhibitor_registrations;
DROP POLICY IF EXISTS "Allow public delete to exhibitor_registrations" ON public.exhibitor_registrations;

DROP POLICY IF EXISTS "Allow public insert to sub_event_registrations" ON public.sub_event_registrations;
DROP POLICY IF EXISTS "Allow public select to sub_event_registrations" ON public.sub_event_registrations;
DROP POLICY IF EXISTS "Allow public delete to sub_event_registrations" ON public.sub_event_registrations;

-- Allow Public Inserts, Selects, and Deletes
CREATE POLICY "Allow public insert to pre_registrations" ON public.pre_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to pre_registrations" ON public.pre_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to pre_registrations" ON public.pre_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to visitor_registrations" ON public.visitor_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to visitor_registrations" ON public.visitor_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to visitor_registrations" ON public.visitor_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to exhibitor_registrations" ON public.exhibitor_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to exhibitor_registrations" ON public.exhibitor_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to exhibitor_registrations" ON public.exhibitor_registrations FOR DELETE USING (true);

CREATE POLICY "Allow public insert to sub_event_registrations" ON public.sub_event_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to sub_event_registrations" ON public.sub_event_registrations FOR SELECT USING (true);
CREATE POLICY "Allow public delete to sub_event_registrations" ON public.sub_event_registrations FOR DELETE USING (true);
